# This is a basic workflow to help you get started with Actions

name: scrape-premier-league-betting-odds

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#   schedule:
#     - cron: "0 */1 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up Python
      - name: 🐍 Set up Python 3.9                             
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.9'

      # Install Requirements
      - name: 💿 Install Requirements                             
        run: pip install -r requirements.txt
        
      # Job
      - name: 🍳 Update dataset
        run: python src/scrape.py
      
      # Commit and push updated dataset
      - name: 🚀 Commit and push if it changed
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
